export const ReasonCodes = {
  policyRejected: "POLICY_REJECTED",
  policyInvalidAgentId: "POLICY_INVALID_AGENT_ID",
  policyInvalidAmount: "POLICY_INVALID_AMOUNT",
  walletAddressUnavailable: "WALLET_ADDRESS_UNAVAILABLE",
  unsupportedIntentAction: "UNSUPPORTED_INTENT_ACTION",
  transferRecipientRequired: "TRANSFER_RECIPIENT_REQUIRED",
  transferAssetRequired: "TRANSFER_ASSET_REQUIRED",
  transferMintRequired: "TRANSFER_MINT_REQUIRED",
  transferSelfNotAllowed: "TRANSFER_SELF_NOT_ALLOWED",
  policyMaxPerTxExceeded: "POLICY_MAX_PER_TX_EXCEEDED",
  policyDslMaxPerTxExceeded: "POLICY_DSL_MAX_PER_TX_EXCEEDED",
  policyDailyCapExceeded: "POLICY_DAILY_CAP_EXCEEDED",
  policyActionNotAllowed: "POLICY_ACTION_NOT_ALLOWED",
  policyMintNotAllowed: "POLICY_MINT_NOT_ALLOWED",
  policySwapMintRequired: "POLICY_SWAP_MINT_REQUIRED",
  policySwapSlippageRequired: "POLICY_SWAP_SLIPPAGE_REQUIRED",
  policyMaxSlippageExceeded: "POLICY_MAX_SLIPPAGE_EXCEEDED",
  policyRuleNotSupported: "POLICY_RULE_NOT_SUPPORTED",
  solanaRpcReadFailed: "SOLANA_RPC_READ_FAILED",
  insufficientFunds: "INSUFFICIENT_FUNDS",
  tokenAccountNotFound: "TOKEN_ACCOUNT_NOT_FOUND",
  tokenSymbolUnsupported: "TOKEN_SYMBOL_UNSUPPORTED",
  splMintMetadataUnavailable: "SPL_MINT_METADATA_UNAVAILABLE",
  swapProtocolUnavailable: "SWAP_PROTOCOL_UNAVAILABLE",
  orcaPoolUnavailable: "ORCA_POOL_UNAVAILABLE",
  orcaBuildFailed: "ORCA_BUILD_FAILED",
  jupiterMainnetOnly: "JUPITER_MAINNET_ONLY",
  raydiumQuoteFailed: "RAYDIUM_QUOTE_FAILED",
  raydiumBuildFailed: "RAYDIUM_BUILD_FAILED",
  policyRpcSimulationUnavailable: "POLICY_RPC_SIMULATION_UNAVAILABLE",
  policyRpcSimulationFailed: "POLICY_RPC_SIMULATION_FAILED",
  txBuildFailed: "TX_BUILD_FAILED",
  signingFailed: "SIGNING_FAILED"
} as const;

export type ReasonCode = (typeof ReasonCodes)[keyof typeof ReasonCodes];
